/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Banner extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Banner\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"w\",\"type\":[\"int\",\"null\"]},{\"name\":\"h\",\"type\":[\"int\",\"null\"]},{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"pos\",\"type\":[\"int\",\"null\"]},{\"name\":\"btype\",\"type\":[{\"type\":\"array\",\"items\":\"int\"},\"null\"]},{\"name\":\"battr\",\"type\":[{\"type\":\"array\",\"items\":\"int\"},\"null\"]},{\"name\":\"mimes\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"]},{\"name\":\"topframe\",\"type\":[\"int\",\"null\"]},{\"name\":\"expdir\",\"type\":[{\"type\":\"array\",\"items\":\"int\"},\"null\"]},{\"name\":\"api\",\"type\":[{\"type\":\"array\",\"items\":\"int\"},\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Integer w;
  @Deprecated public java.lang.Integer h;
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.Integer pos;
  @Deprecated public java.util.List<java.lang.Integer> btype;
  @Deprecated public java.util.List<java.lang.Integer> battr;
  @Deprecated public java.util.List<java.lang.CharSequence> mimes;
  @Deprecated public java.lang.Integer topframe;
  @Deprecated public java.util.List<java.lang.Integer> expdir;
  @Deprecated public java.util.List<java.lang.Integer> api;
  @Deprecated public java.lang.CharSequence ext;

  /**
   * Default constructor.
   */
  public Banner() {}

  /**
   * All-args constructor.
   */
  public Banner(java.lang.Integer w, java.lang.Integer h, java.lang.CharSequence id, java.lang.Integer pos, java.util.List<java.lang.Integer> btype, java.util.List<java.lang.Integer> battr, java.util.List<java.lang.CharSequence> mimes, java.lang.Integer topframe, java.util.List<java.lang.Integer> expdir, java.util.List<java.lang.Integer> api, java.lang.CharSequence ext) {
    this.w = w;
    this.h = h;
    this.id = id;
    this.pos = pos;
    this.btype = btype;
    this.battr = battr;
    this.mimes = mimes;
    this.topframe = topframe;
    this.expdir = expdir;
    this.api = api;
    this.ext = ext;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return w;
    case 1: return h;
    case 2: return id;
    case 3: return pos;
    case 4: return btype;
    case 5: return battr;
    case 6: return mimes;
    case 7: return topframe;
    case 8: return expdir;
    case 9: return api;
    case 10: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: w = (java.lang.Integer)value$; break;
    case 1: h = (java.lang.Integer)value$; break;
    case 2: id = (java.lang.CharSequence)value$; break;
    case 3: pos = (java.lang.Integer)value$; break;
    case 4: btype = (java.util.List<java.lang.Integer>)value$; break;
    case 5: battr = (java.util.List<java.lang.Integer>)value$; break;
    case 6: mimes = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: topframe = (java.lang.Integer)value$; break;
    case 8: expdir = (java.util.List<java.lang.Integer>)value$; break;
    case 9: api = (java.util.List<java.lang.Integer>)value$; break;
    case 10: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'w' field.
   */
  public java.lang.Integer getW() {
    return w;
  }

  /**
   * Sets the value of the 'w' field.
   * @param value the value to set.
   */
  public void setW(java.lang.Integer value) {
    this.w = value;
  }

  /**
   * Gets the value of the 'h' field.
   */
  public java.lang.Integer getH() {
    return h;
  }

  /**
   * Sets the value of the 'h' field.
   * @param value the value to set.
   */
  public void setH(java.lang.Integer value) {
    this.h = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'pos' field.
   */
  public java.lang.Integer getPos() {
    return pos;
  }

  /**
   * Sets the value of the 'pos' field.
   * @param value the value to set.
   */
  public void setPos(java.lang.Integer value) {
    this.pos = value;
  }

  /**
   * Gets the value of the 'btype' field.
   */
  public java.util.List<java.lang.Integer> getBtype() {
    return btype;
  }

  /**
   * Sets the value of the 'btype' field.
   * @param value the value to set.
   */
  public void setBtype(java.util.List<java.lang.Integer> value) {
    this.btype = value;
  }

  /**
   * Gets the value of the 'battr' field.
   */
  public java.util.List<java.lang.Integer> getBattr() {
    return battr;
  }

  /**
   * Sets the value of the 'battr' field.
   * @param value the value to set.
   */
  public void setBattr(java.util.List<java.lang.Integer> value) {
    this.battr = value;
  }

  /**
   * Gets the value of the 'mimes' field.
   */
  public java.util.List<java.lang.CharSequence> getMimes() {
    return mimes;
  }

  /**
   * Sets the value of the 'mimes' field.
   * @param value the value to set.
   */
  public void setMimes(java.util.List<java.lang.CharSequence> value) {
    this.mimes = value;
  }

  /**
   * Gets the value of the 'topframe' field.
   */
  public java.lang.Integer getTopframe() {
    return topframe;
  }

  /**
   * Sets the value of the 'topframe' field.
   * @param value the value to set.
   */
  public void setTopframe(java.lang.Integer value) {
    this.topframe = value;
  }

  /**
   * Gets the value of the 'expdir' field.
   */
  public java.util.List<java.lang.Integer> getExpdir() {
    return expdir;
  }

  /**
   * Sets the value of the 'expdir' field.
   * @param value the value to set.
   */
  public void setExpdir(java.util.List<java.lang.Integer> value) {
    this.expdir = value;
  }

  /**
   * Gets the value of the 'api' field.
   */
  public java.util.List<java.lang.Integer> getApi() {
    return api;
  }

  /**
   * Sets the value of the 'api' field.
   * @param value the value to set.
   */
  public void setApi(java.util.List<java.lang.Integer> value) {
    this.api = value;
  }

  /**
   * Gets the value of the 'ext' field.
   */
  public java.lang.CharSequence getExt() {
    return ext;
  }

  /**
   * Sets the value of the 'ext' field.
   * @param value the value to set.
   */
  public void setExt(java.lang.CharSequence value) {
    this.ext = value;
  }

  /** Creates a new Banner RecordBuilder */
  public static org.openrtb.common.api.Banner.Builder newBuilder() {
    return new org.openrtb.common.api.Banner.Builder();
  }
  
  /** Creates a new Banner RecordBuilder by copying an existing Builder */
  public static org.openrtb.common.api.Banner.Builder newBuilder(org.openrtb.common.api.Banner.Builder other) {
    return new org.openrtb.common.api.Banner.Builder(other);
  }
  
  /** Creates a new Banner RecordBuilder by copying an existing Banner instance */
  public static org.openrtb.common.api.Banner.Builder newBuilder(org.openrtb.common.api.Banner other) {
    return new org.openrtb.common.api.Banner.Builder(other);
  }
  
  /**
   * RecordBuilder for Banner instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Banner>
    implements org.apache.avro.data.RecordBuilder<Banner> {

    private java.lang.Integer w;
    private java.lang.Integer h;
    private java.lang.CharSequence id;
    private java.lang.Integer pos;
    private java.util.List<java.lang.Integer> btype;
    private java.util.List<java.lang.Integer> battr;
    private java.util.List<java.lang.CharSequence> mimes;
    private java.lang.Integer topframe;
    private java.util.List<java.lang.Integer> expdir;
    private java.util.List<java.lang.Integer> api;
    private java.lang.CharSequence ext;

    /** Creates a new Builder */
    private Builder() {
      super(org.openrtb.common.api.Banner.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.openrtb.common.api.Banner.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Banner instance */
    private Builder(org.openrtb.common.api.Banner other) {
            super(org.openrtb.common.api.Banner.SCHEMA$);
      if (isValidValue(fields()[0], other.w)) {
        this.w = data().deepCopy(fields()[0].schema(), other.w);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.h)) {
        this.h = data().deepCopy(fields()[1].schema(), other.h);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.id)) {
        this.id = data().deepCopy(fields()[2].schema(), other.id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pos)) {
        this.pos = data().deepCopy(fields()[3].schema(), other.pos);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.btype)) {
        this.btype = data().deepCopy(fields()[4].schema(), other.btype);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.battr)) {
        this.battr = data().deepCopy(fields()[5].schema(), other.battr);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.mimes)) {
        this.mimes = data().deepCopy(fields()[6].schema(), other.mimes);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.topframe)) {
        this.topframe = data().deepCopy(fields()[7].schema(), other.topframe);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.expdir)) {
        this.expdir = data().deepCopy(fields()[8].schema(), other.expdir);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.api)) {
        this.api = data().deepCopy(fields()[9].schema(), other.api);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ext)) {
        this.ext = data().deepCopy(fields()[10].schema(), other.ext);
        fieldSetFlags()[10] = true;
      }
    }

    /** Gets the value of the 'w' field */
    public java.lang.Integer getW() {
      return w;
    }
    
    /** Sets the value of the 'w' field */
    public org.openrtb.common.api.Banner.Builder setW(java.lang.Integer value) {
      validate(fields()[0], value);
      this.w = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'w' field has been set */
    public boolean hasW() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'w' field */
    public org.openrtb.common.api.Banner.Builder clearW() {
      w = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'h' field */
    public java.lang.Integer getH() {
      return h;
    }
    
    /** Sets the value of the 'h' field */
    public org.openrtb.common.api.Banner.Builder setH(java.lang.Integer value) {
      validate(fields()[1], value);
      this.h = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'h' field has been set */
    public boolean hasH() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'h' field */
    public org.openrtb.common.api.Banner.Builder clearH() {
      h = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.openrtb.common.api.Banner.Builder setId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'id' field */
    public org.openrtb.common.api.Banner.Builder clearId() {
      id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'pos' field */
    public java.lang.Integer getPos() {
      return pos;
    }
    
    /** Sets the value of the 'pos' field */
    public org.openrtb.common.api.Banner.Builder setPos(java.lang.Integer value) {
      validate(fields()[3], value);
      this.pos = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'pos' field has been set */
    public boolean hasPos() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'pos' field */
    public org.openrtb.common.api.Banner.Builder clearPos() {
      pos = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'btype' field */
    public java.util.List<java.lang.Integer> getBtype() {
      return btype;
    }
    
    /** Sets the value of the 'btype' field */
    public org.openrtb.common.api.Banner.Builder setBtype(java.util.List<java.lang.Integer> value) {
      validate(fields()[4], value);
      this.btype = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'btype' field has been set */
    public boolean hasBtype() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'btype' field */
    public org.openrtb.common.api.Banner.Builder clearBtype() {
      btype = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'battr' field */
    public java.util.List<java.lang.Integer> getBattr() {
      return battr;
    }
    
    /** Sets the value of the 'battr' field */
    public org.openrtb.common.api.Banner.Builder setBattr(java.util.List<java.lang.Integer> value) {
      validate(fields()[5], value);
      this.battr = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'battr' field has been set */
    public boolean hasBattr() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'battr' field */
    public org.openrtb.common.api.Banner.Builder clearBattr() {
      battr = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'mimes' field */
    public java.util.List<java.lang.CharSequence> getMimes() {
      return mimes;
    }
    
    /** Sets the value of the 'mimes' field */
    public org.openrtb.common.api.Banner.Builder setMimes(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[6], value);
      this.mimes = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'mimes' field has been set */
    public boolean hasMimes() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'mimes' field */
    public org.openrtb.common.api.Banner.Builder clearMimes() {
      mimes = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'topframe' field */
    public java.lang.Integer getTopframe() {
      return topframe;
    }
    
    /** Sets the value of the 'topframe' field */
    public org.openrtb.common.api.Banner.Builder setTopframe(java.lang.Integer value) {
      validate(fields()[7], value);
      this.topframe = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'topframe' field has been set */
    public boolean hasTopframe() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'topframe' field */
    public org.openrtb.common.api.Banner.Builder clearTopframe() {
      topframe = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'expdir' field */
    public java.util.List<java.lang.Integer> getExpdir() {
      return expdir;
    }
    
    /** Sets the value of the 'expdir' field */
    public org.openrtb.common.api.Banner.Builder setExpdir(java.util.List<java.lang.Integer> value) {
      validate(fields()[8], value);
      this.expdir = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'expdir' field has been set */
    public boolean hasExpdir() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'expdir' field */
    public org.openrtb.common.api.Banner.Builder clearExpdir() {
      expdir = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'api' field */
    public java.util.List<java.lang.Integer> getApi() {
      return api;
    }
    
    /** Sets the value of the 'api' field */
    public org.openrtb.common.api.Banner.Builder setApi(java.util.List<java.lang.Integer> value) {
      validate(fields()[9], value);
      this.api = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'api' field has been set */
    public boolean hasApi() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'api' field */
    public org.openrtb.common.api.Banner.Builder clearApi() {
      api = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'ext' field */
    public java.lang.CharSequence getExt() {
      return ext;
    }
    
    /** Sets the value of the 'ext' field */
    public org.openrtb.common.api.Banner.Builder setExt(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.ext = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'ext' field has been set */
    public boolean hasExt() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'ext' field */
    public org.openrtb.common.api.Banner.Builder clearExt() {
      ext = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    public Banner build() {
      try {
        Banner record = new Banner();
        record.w = fieldSetFlags()[0] ? this.w : (java.lang.Integer) defaultValue(fields()[0]);
        record.h = fieldSetFlags()[1] ? this.h : (java.lang.Integer) defaultValue(fields()[1]);
        record.id = fieldSetFlags()[2] ? this.id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.pos = fieldSetFlags()[3] ? this.pos : (java.lang.Integer) defaultValue(fields()[3]);
        record.btype = fieldSetFlags()[4] ? this.btype : (java.util.List<java.lang.Integer>) defaultValue(fields()[4]);
        record.battr = fieldSetFlags()[5] ? this.battr : (java.util.List<java.lang.Integer>) defaultValue(fields()[5]);
        record.mimes = fieldSetFlags()[6] ? this.mimes : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[6]);
        record.topframe = fieldSetFlags()[7] ? this.topframe : (java.lang.Integer) defaultValue(fields()[7]);
        record.expdir = fieldSetFlags()[8] ? this.expdir : (java.util.List<java.lang.Integer>) defaultValue(fields()[8]);
        record.api = fieldSetFlags()[9] ? this.api : (java.util.List<java.lang.Integer>) defaultValue(fields()[9]);
        record.ext = fieldSetFlags()[10] ? this.ext : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
