/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Bid extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Bid\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"impid\",\"type\":[\"string\",\"null\"]},{\"name\":\"price\",\"type\":[\"float\",\"null\"]},{\"name\":\"adid\",\"type\":[\"string\",\"null\"]},{\"name\":\"nurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"adm\",\"type\":[\"string\",\"null\"]},{\"name\":\"adomain\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"]},{\"name\":\"iurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"cid\",\"type\":[\"string\",\"null\"]},{\"name\":\"crid\",\"type\":[\"string\",\"null\"]},{\"name\":\"attr\",\"type\":[{\"type\":\"array\",\"items\":\"int\"},\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence impid;
  @Deprecated public java.lang.Float price;
  @Deprecated public java.lang.CharSequence adid;
  @Deprecated public java.lang.CharSequence nurl;
  @Deprecated public java.lang.CharSequence adm;
  @Deprecated public java.util.List<java.lang.CharSequence> adomain;
  @Deprecated public java.lang.CharSequence iurl;
  @Deprecated public java.lang.CharSequence cid;
  @Deprecated public java.lang.CharSequence crid;
  @Deprecated public java.util.List<java.lang.Integer> attr;
  @Deprecated public java.lang.CharSequence ext;

  /**
   * Default constructor.
   */
  public Bid() {}

  /**
   * All-args constructor.
   */
  public Bid(java.lang.CharSequence id, java.lang.CharSequence impid, java.lang.Float price, java.lang.CharSequence adid, java.lang.CharSequence nurl, java.lang.CharSequence adm, java.util.List<java.lang.CharSequence> adomain, java.lang.CharSequence iurl, java.lang.CharSequence cid, java.lang.CharSequence crid, java.util.List<java.lang.Integer> attr, java.lang.CharSequence ext) {
    this.id = id;
    this.impid = impid;
    this.price = price;
    this.adid = adid;
    this.nurl = nurl;
    this.adm = adm;
    this.adomain = adomain;
    this.iurl = iurl;
    this.cid = cid;
    this.crid = crid;
    this.attr = attr;
    this.ext = ext;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return impid;
    case 2: return price;
    case 3: return adid;
    case 4: return nurl;
    case 5: return adm;
    case 6: return adomain;
    case 7: return iurl;
    case 8: return cid;
    case 9: return crid;
    case 10: return attr;
    case 11: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: impid = (java.lang.CharSequence)value$; break;
    case 2: price = (java.lang.Float)value$; break;
    case 3: adid = (java.lang.CharSequence)value$; break;
    case 4: nurl = (java.lang.CharSequence)value$; break;
    case 5: adm = (java.lang.CharSequence)value$; break;
    case 6: adomain = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: iurl = (java.lang.CharSequence)value$; break;
    case 8: cid = (java.lang.CharSequence)value$; break;
    case 9: crid = (java.lang.CharSequence)value$; break;
    case 10: attr = (java.util.List<java.lang.Integer>)value$; break;
    case 11: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'impid' field.
   */
  public java.lang.CharSequence getImpid() {
    return impid;
  }

  /**
   * Sets the value of the 'impid' field.
   * @param value the value to set.
   */
  public void setImpid(java.lang.CharSequence value) {
    this.impid = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public java.lang.Float getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Float value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'adid' field.
   */
  public java.lang.CharSequence getAdid() {
    return adid;
  }

  /**
   * Sets the value of the 'adid' field.
   * @param value the value to set.
   */
  public void setAdid(java.lang.CharSequence value) {
    this.adid = value;
  }

  /**
   * Gets the value of the 'nurl' field.
   */
  public java.lang.CharSequence getNurl() {
    return nurl;
  }

  /**
   * Sets the value of the 'nurl' field.
   * @param value the value to set.
   */
  public void setNurl(java.lang.CharSequence value) {
    this.nurl = value;
  }

  /**
   * Gets the value of the 'adm' field.
   */
  public java.lang.CharSequence getAdm() {
    return adm;
  }

  /**
   * Sets the value of the 'adm' field.
   * @param value the value to set.
   */
  public void setAdm(java.lang.CharSequence value) {
    this.adm = value;
  }

  /**
   * Gets the value of the 'adomain' field.
   */
  public java.util.List<java.lang.CharSequence> getAdomain() {
    return adomain;
  }

  /**
   * Sets the value of the 'adomain' field.
   * @param value the value to set.
   */
  public void setAdomain(java.util.List<java.lang.CharSequence> value) {
    this.adomain = value;
  }

  /**
   * Gets the value of the 'iurl' field.
   */
  public java.lang.CharSequence getIurl() {
    return iurl;
  }

  /**
   * Sets the value of the 'iurl' field.
   * @param value the value to set.
   */
  public void setIurl(java.lang.CharSequence value) {
    this.iurl = value;
  }

  /**
   * Gets the value of the 'cid' field.
   */
  public java.lang.CharSequence getCid() {
    return cid;
  }

  /**
   * Sets the value of the 'cid' field.
   * @param value the value to set.
   */
  public void setCid(java.lang.CharSequence value) {
    this.cid = value;
  }

  /**
   * Gets the value of the 'crid' field.
   */
  public java.lang.CharSequence getCrid() {
    return crid;
  }

  /**
   * Sets the value of the 'crid' field.
   * @param value the value to set.
   */
  public void setCrid(java.lang.CharSequence value) {
    this.crid = value;
  }

  /**
   * Gets the value of the 'attr' field.
   */
  public java.util.List<java.lang.Integer> getAttr() {
    return attr;
  }

  /**
   * Sets the value of the 'attr' field.
   * @param value the value to set.
   */
  public void setAttr(java.util.List<java.lang.Integer> value) {
    this.attr = value;
  }

  /**
   * Gets the value of the 'ext' field.
   */
  public java.lang.CharSequence getExt() {
    return ext;
  }

  /**
   * Sets the value of the 'ext' field.
   * @param value the value to set.
   */
  public void setExt(java.lang.CharSequence value) {
    this.ext = value;
  }

  /** Creates a new Bid RecordBuilder */
  public static org.openrtb.common.api.Bid.Builder newBuilder() {
    return new org.openrtb.common.api.Bid.Builder();
  }
  
  /** Creates a new Bid RecordBuilder by copying an existing Builder */
  public static org.openrtb.common.api.Bid.Builder newBuilder(org.openrtb.common.api.Bid.Builder other) {
    return new org.openrtb.common.api.Bid.Builder(other);
  }
  
  /** Creates a new Bid RecordBuilder by copying an existing Bid instance */
  public static org.openrtb.common.api.Bid.Builder newBuilder(org.openrtb.common.api.Bid other) {
    return new org.openrtb.common.api.Bid.Builder(other);
  }
  
  /**
   * RecordBuilder for Bid instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Bid>
    implements org.apache.avro.data.RecordBuilder<Bid> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence impid;
    private java.lang.Float price;
    private java.lang.CharSequence adid;
    private java.lang.CharSequence nurl;
    private java.lang.CharSequence adm;
    private java.util.List<java.lang.CharSequence> adomain;
    private java.lang.CharSequence iurl;
    private java.lang.CharSequence cid;
    private java.lang.CharSequence crid;
    private java.util.List<java.lang.Integer> attr;
    private java.lang.CharSequence ext;

    /** Creates a new Builder */
    private Builder() {
      super(org.openrtb.common.api.Bid.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.openrtb.common.api.Bid.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Bid instance */
    private Builder(org.openrtb.common.api.Bid other) {
            super(org.openrtb.common.api.Bid.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.impid)) {
        this.impid = data().deepCopy(fields()[1].schema(), other.impid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.adid)) {
        this.adid = data().deepCopy(fields()[3].schema(), other.adid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.nurl)) {
        this.nurl = data().deepCopy(fields()[4].schema(), other.nurl);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.adm)) {
        this.adm = data().deepCopy(fields()[5].schema(), other.adm);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.adomain)) {
        this.adomain = data().deepCopy(fields()[6].schema(), other.adomain);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.iurl)) {
        this.iurl = data().deepCopy(fields()[7].schema(), other.iurl);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.cid)) {
        this.cid = data().deepCopy(fields()[8].schema(), other.cid);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.crid)) {
        this.crid = data().deepCopy(fields()[9].schema(), other.crid);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.attr)) {
        this.attr = data().deepCopy(fields()[10].schema(), other.attr);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ext)) {
        this.ext = data().deepCopy(fields()[11].schema(), other.ext);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.openrtb.common.api.Bid.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.openrtb.common.api.Bid.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'impid' field */
    public java.lang.CharSequence getImpid() {
      return impid;
    }
    
    /** Sets the value of the 'impid' field */
    public org.openrtb.common.api.Bid.Builder setImpid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.impid = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'impid' field has been set */
    public boolean hasImpid() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'impid' field */
    public org.openrtb.common.api.Bid.Builder clearImpid() {
      impid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public java.lang.Float getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public org.openrtb.common.api.Bid.Builder setPrice(java.lang.Float value) {
      validate(fields()[2], value);
      this.price = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'price' field */
    public org.openrtb.common.api.Bid.Builder clearPrice() {
      price = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'adid' field */
    public java.lang.CharSequence getAdid() {
      return adid;
    }
    
    /** Sets the value of the 'adid' field */
    public org.openrtb.common.api.Bid.Builder setAdid(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.adid = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'adid' field has been set */
    public boolean hasAdid() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'adid' field */
    public org.openrtb.common.api.Bid.Builder clearAdid() {
      adid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'nurl' field */
    public java.lang.CharSequence getNurl() {
      return nurl;
    }
    
    /** Sets the value of the 'nurl' field */
    public org.openrtb.common.api.Bid.Builder setNurl(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.nurl = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'nurl' field has been set */
    public boolean hasNurl() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'nurl' field */
    public org.openrtb.common.api.Bid.Builder clearNurl() {
      nurl = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'adm' field */
    public java.lang.CharSequence getAdm() {
      return adm;
    }
    
    /** Sets the value of the 'adm' field */
    public org.openrtb.common.api.Bid.Builder setAdm(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.adm = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'adm' field has been set */
    public boolean hasAdm() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'adm' field */
    public org.openrtb.common.api.Bid.Builder clearAdm() {
      adm = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'adomain' field */
    public java.util.List<java.lang.CharSequence> getAdomain() {
      return adomain;
    }
    
    /** Sets the value of the 'adomain' field */
    public org.openrtb.common.api.Bid.Builder setAdomain(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[6], value);
      this.adomain = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'adomain' field has been set */
    public boolean hasAdomain() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'adomain' field */
    public org.openrtb.common.api.Bid.Builder clearAdomain() {
      adomain = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'iurl' field */
    public java.lang.CharSequence getIurl() {
      return iurl;
    }
    
    /** Sets the value of the 'iurl' field */
    public org.openrtb.common.api.Bid.Builder setIurl(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.iurl = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'iurl' field has been set */
    public boolean hasIurl() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'iurl' field */
    public org.openrtb.common.api.Bid.Builder clearIurl() {
      iurl = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'cid' field */
    public java.lang.CharSequence getCid() {
      return cid;
    }
    
    /** Sets the value of the 'cid' field */
    public org.openrtb.common.api.Bid.Builder setCid(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.cid = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'cid' field has been set */
    public boolean hasCid() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'cid' field */
    public org.openrtb.common.api.Bid.Builder clearCid() {
      cid = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'crid' field */
    public java.lang.CharSequence getCrid() {
      return crid;
    }
    
    /** Sets the value of the 'crid' field */
    public org.openrtb.common.api.Bid.Builder setCrid(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.crid = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'crid' field has been set */
    public boolean hasCrid() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'crid' field */
    public org.openrtb.common.api.Bid.Builder clearCrid() {
      crid = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'attr' field */
    public java.util.List<java.lang.Integer> getAttr() {
      return attr;
    }
    
    /** Sets the value of the 'attr' field */
    public org.openrtb.common.api.Bid.Builder setAttr(java.util.List<java.lang.Integer> value) {
      validate(fields()[10], value);
      this.attr = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'attr' field has been set */
    public boolean hasAttr() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'attr' field */
    public org.openrtb.common.api.Bid.Builder clearAttr() {
      attr = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'ext' field */
    public java.lang.CharSequence getExt() {
      return ext;
    }
    
    /** Sets the value of the 'ext' field */
    public org.openrtb.common.api.Bid.Builder setExt(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.ext = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'ext' field has been set */
    public boolean hasExt() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'ext' field */
    public org.openrtb.common.api.Bid.Builder clearExt() {
      ext = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public Bid build() {
      try {
        Bid record = new Bid();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.impid = fieldSetFlags()[1] ? this.impid : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.price = fieldSetFlags()[2] ? this.price : (java.lang.Float) defaultValue(fields()[2]);
        record.adid = fieldSetFlags()[3] ? this.adid : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.nurl = fieldSetFlags()[4] ? this.nurl : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.adm = fieldSetFlags()[5] ? this.adm : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.adomain = fieldSetFlags()[6] ? this.adomain : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[6]);
        record.iurl = fieldSetFlags()[7] ? this.iurl : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.cid = fieldSetFlags()[8] ? this.cid : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.crid = fieldSetFlags()[9] ? this.crid : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.attr = fieldSetFlags()[10] ? this.attr : (java.util.List<java.lang.Integer>) defaultValue(fields()[10]);
        record.ext = fieldSetFlags()[11] ? this.ext : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
