/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BidResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BidResponse\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"seatbid\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SeatBid\",\"fields\":[{\"name\":\"bid\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Bid\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"impid\",\"type\":[\"string\",\"null\"]},{\"name\":\"price\",\"type\":[\"float\",\"null\"]},{\"name\":\"adid\",\"type\":[\"string\",\"null\"]},{\"name\":\"nurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"adm\",\"type\":[\"string\",\"null\"]},{\"name\":\"adomain\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"]},{\"name\":\"iurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"cid\",\"type\":[\"string\",\"null\"]},{\"name\":\"crid\",\"type\":[\"string\",\"null\"]},{\"name\":\"attr\",\"type\":[{\"type\":\"array\",\"items\":\"int\"},\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}}},{\"name\":\"seat\",\"type\":[\"string\",\"null\"]},{\"name\":\"group\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}}},{\"name\":\"bidid\",\"type\":[\"string\",\"null\"]},{\"name\":\"cur\",\"type\":[\"string\",\"null\"]},{\"name\":\"customdata\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.util.List<org.openrtb.common.api.SeatBid> seatbid;
  @Deprecated public java.lang.CharSequence bidid;
  @Deprecated public java.lang.CharSequence cur;
  @Deprecated public java.lang.CharSequence customdata;
  @Deprecated public java.lang.CharSequence ext;

  /**
   * Default constructor.
   */
  public BidResponse() {}

  /**
   * All-args constructor.
   */
  public BidResponse(java.lang.CharSequence id, java.util.List<org.openrtb.common.api.SeatBid> seatbid, java.lang.CharSequence bidid, java.lang.CharSequence cur, java.lang.CharSequence customdata, java.lang.CharSequence ext) {
    this.id = id;
    this.seatbid = seatbid;
    this.bidid = bidid;
    this.cur = cur;
    this.customdata = customdata;
    this.ext = ext;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return seatbid;
    case 2: return bidid;
    case 3: return cur;
    case 4: return customdata;
    case 5: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: seatbid = (java.util.List<org.openrtb.common.api.SeatBid>)value$; break;
    case 2: bidid = (java.lang.CharSequence)value$; break;
    case 3: cur = (java.lang.CharSequence)value$; break;
    case 4: customdata = (java.lang.CharSequence)value$; break;
    case 5: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'seatbid' field.
   */
  public java.util.List<org.openrtb.common.api.SeatBid> getSeatbid() {
    return seatbid;
  }

  /**
   * Sets the value of the 'seatbid' field.
   * @param value the value to set.
   */
  public void setSeatbid(java.util.List<org.openrtb.common.api.SeatBid> value) {
    this.seatbid = value;
  }

  /**
   * Gets the value of the 'bidid' field.
   */
  public java.lang.CharSequence getBidid() {
    return bidid;
  }

  /**
   * Sets the value of the 'bidid' field.
   * @param value the value to set.
   */
  public void setBidid(java.lang.CharSequence value) {
    this.bidid = value;
  }

  /**
   * Gets the value of the 'cur' field.
   */
  public java.lang.CharSequence getCur() {
    return cur;
  }

  /**
   * Sets the value of the 'cur' field.
   * @param value the value to set.
   */
  public void setCur(java.lang.CharSequence value) {
    this.cur = value;
  }

  /**
   * Gets the value of the 'customdata' field.
   */
  public java.lang.CharSequence getCustomdata() {
    return customdata;
  }

  /**
   * Sets the value of the 'customdata' field.
   * @param value the value to set.
   */
  public void setCustomdata(java.lang.CharSequence value) {
    this.customdata = value;
  }

  /**
   * Gets the value of the 'ext' field.
   */
  public java.lang.CharSequence getExt() {
    return ext;
  }

  /**
   * Sets the value of the 'ext' field.
   * @param value the value to set.
   */
  public void setExt(java.lang.CharSequence value) {
    this.ext = value;
  }

  /** Creates a new BidResponse RecordBuilder */
  public static org.openrtb.common.api.BidResponse.Builder newBuilder() {
    return new org.openrtb.common.api.BidResponse.Builder();
  }
  
  /** Creates a new BidResponse RecordBuilder by copying an existing Builder */
  public static org.openrtb.common.api.BidResponse.Builder newBuilder(org.openrtb.common.api.BidResponse.Builder other) {
    return new org.openrtb.common.api.BidResponse.Builder(other);
  }
  
  /** Creates a new BidResponse RecordBuilder by copying an existing BidResponse instance */
  public static org.openrtb.common.api.BidResponse.Builder newBuilder(org.openrtb.common.api.BidResponse other) {
    return new org.openrtb.common.api.BidResponse.Builder(other);
  }
  
  /**
   * RecordBuilder for BidResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BidResponse>
    implements org.apache.avro.data.RecordBuilder<BidResponse> {

    private java.lang.CharSequence id;
    private java.util.List<org.openrtb.common.api.SeatBid> seatbid;
    private java.lang.CharSequence bidid;
    private java.lang.CharSequence cur;
    private java.lang.CharSequence customdata;
    private java.lang.CharSequence ext;

    /** Creates a new Builder */
    private Builder() {
      super(org.openrtb.common.api.BidResponse.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.openrtb.common.api.BidResponse.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing BidResponse instance */
    private Builder(org.openrtb.common.api.BidResponse other) {
            super(org.openrtb.common.api.BidResponse.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.seatbid)) {
        this.seatbid = data().deepCopy(fields()[1].schema(), other.seatbid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bidid)) {
        this.bidid = data().deepCopy(fields()[2].schema(), other.bidid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cur)) {
        this.cur = data().deepCopy(fields()[3].schema(), other.cur);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customdata)) {
        this.customdata = data().deepCopy(fields()[4].schema(), other.customdata);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ext)) {
        this.ext = data().deepCopy(fields()[5].schema(), other.ext);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.openrtb.common.api.BidResponse.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.openrtb.common.api.BidResponse.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'seatbid' field */
    public java.util.List<org.openrtb.common.api.SeatBid> getSeatbid() {
      return seatbid;
    }
    
    /** Sets the value of the 'seatbid' field */
    public org.openrtb.common.api.BidResponse.Builder setSeatbid(java.util.List<org.openrtb.common.api.SeatBid> value) {
      validate(fields()[1], value);
      this.seatbid = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'seatbid' field has been set */
    public boolean hasSeatbid() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'seatbid' field */
    public org.openrtb.common.api.BidResponse.Builder clearSeatbid() {
      seatbid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'bidid' field */
    public java.lang.CharSequence getBidid() {
      return bidid;
    }
    
    /** Sets the value of the 'bidid' field */
    public org.openrtb.common.api.BidResponse.Builder setBidid(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.bidid = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'bidid' field has been set */
    public boolean hasBidid() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'bidid' field */
    public org.openrtb.common.api.BidResponse.Builder clearBidid() {
      bidid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'cur' field */
    public java.lang.CharSequence getCur() {
      return cur;
    }
    
    /** Sets the value of the 'cur' field */
    public org.openrtb.common.api.BidResponse.Builder setCur(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.cur = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'cur' field has been set */
    public boolean hasCur() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'cur' field */
    public org.openrtb.common.api.BidResponse.Builder clearCur() {
      cur = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'customdata' field */
    public java.lang.CharSequence getCustomdata() {
      return customdata;
    }
    
    /** Sets the value of the 'customdata' field */
    public org.openrtb.common.api.BidResponse.Builder setCustomdata(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.customdata = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'customdata' field has been set */
    public boolean hasCustomdata() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'customdata' field */
    public org.openrtb.common.api.BidResponse.Builder clearCustomdata() {
      customdata = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'ext' field */
    public java.lang.CharSequence getExt() {
      return ext;
    }
    
    /** Sets the value of the 'ext' field */
    public org.openrtb.common.api.BidResponse.Builder setExt(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.ext = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'ext' field has been set */
    public boolean hasExt() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'ext' field */
    public org.openrtb.common.api.BidResponse.Builder clearExt() {
      ext = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public BidResponse build() {
      try {
        BidResponse record = new BidResponse();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.seatbid = fieldSetFlags()[1] ? this.seatbid : (java.util.List<org.openrtb.common.api.SeatBid>) defaultValue(fields()[1]);
        record.bidid = fieldSetFlags()[2] ? this.bidid : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.cur = fieldSetFlags()[3] ? this.cur : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.customdata = fieldSetFlags()[4] ? this.customdata : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.ext = fieldSetFlags()[5] ? this.ext : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
