/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Content extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Content\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"episode\",\"type\":[\"int\",\"null\"]},{\"name\":\"title\",\"type\":[\"string\",\"null\"]},{\"name\":\"series\",\"type\":[\"string\",\"null\"]},{\"name\":\"season\",\"type\":[\"string\",\"null\"]},{\"name\":\"url\",\"type\":[\"string\",\"null\"]},{\"name\":\"cat\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"videoquality\",\"type\":[\"int\",\"null\"]},{\"name\":\"keywords\",\"type\":[\"string\",\"null\"]},{\"name\":\"contentrating\",\"type\":[\"string\",\"null\"]},{\"name\":\"userrating\",\"type\":[\"string\",\"null\"]},{\"name\":\"context\",\"type\":[\"string\",\"null\"]},{\"name\":\"livestream\",\"type\":[\"int\",\"null\"]},{\"name\":\"sourcerelationship\",\"type\":[\"int\",\"null\"]},{\"name\":\"producer\",\"type\":[{\"type\":\"record\",\"name\":\"Producer\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"name\",\"type\":[\"string\",\"null\"]},{\"name\":\"cat\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"domain\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]},\"null\"]},{\"name\":\"len\",\"type\":[\"int\",\"null\"]},{\"name\":\"qagmediarating\",\"type\":[\"int\",\"null\"]},{\"name\":\"embeddable\",\"type\":[\"int\",\"null\"]},{\"name\":\"language\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.CharSequence id;
   public java.lang.Integer episode;
   public java.lang.CharSequence title;
   public java.lang.CharSequence series;
   public java.lang.CharSequence season;
   public java.lang.CharSequence url;
   public java.util.List<java.lang.CharSequence> cat;
   public java.lang.Integer videoquality;
   public java.lang.CharSequence keywords;
   public java.lang.CharSequence contentrating;
   public java.lang.CharSequence userrating;
   public java.lang.CharSequence context;
   public java.lang.Integer livestream;
   public java.lang.Integer sourcerelationship;
   public org.openrtb.common.api.Producer producer;
   public java.lang.Integer len;
   public java.lang.Integer qagmediarating;
   public java.lang.Integer embeddable;
   public java.lang.CharSequence language;
   public java.lang.CharSequence ext;

  /**
   * Default constructor.
   */
  public Content() {}

  /**
   * All-args constructor.
   */
  public Content(java.lang.CharSequence id, java.lang.Integer episode, java.lang.CharSequence title, java.lang.CharSequence series, java.lang.CharSequence season, java.lang.CharSequence url, java.util.List<java.lang.CharSequence> cat, java.lang.Integer videoquality, java.lang.CharSequence keywords, java.lang.CharSequence contentrating, java.lang.CharSequence userrating, java.lang.CharSequence context, java.lang.Integer livestream, java.lang.Integer sourcerelationship, org.openrtb.common.api.Producer producer, java.lang.Integer len, java.lang.Integer qagmediarating, java.lang.Integer embeddable, java.lang.CharSequence language, java.lang.CharSequence ext) {
    this.id = id;
    this.episode = episode;
    this.title = title;
    this.series = series;
    this.season = season;
    this.url = url;
    this.cat = cat;
    this.videoquality = videoquality;
    this.keywords = keywords;
    this.contentrating = contentrating;
    this.userrating = userrating;
    this.context = context;
    this.livestream = livestream;
    this.sourcerelationship = sourcerelationship;
    this.producer = producer;
    this.len = len;
    this.qagmediarating = qagmediarating;
    this.embeddable = embeddable;
    this.language = language;
    this.ext = ext;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return episode;
    case 2: return title;
    case 3: return series;
    case 4: return season;
    case 5: return url;
    case 6: return cat;
    case 7: return videoquality;
    case 8: return keywords;
    case 9: return contentrating;
    case 10: return userrating;
    case 11: return context;
    case 12: return livestream;
    case 13: return sourcerelationship;
    case 14: return producer;
    case 15: return len;
    case 16: return qagmediarating;
    case 17: return embeddable;
    case 18: return language;
    case 19: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: episode = (java.lang.Integer)value$; break;
    case 2: title = (java.lang.CharSequence)value$; break;
    case 3: series = (java.lang.CharSequence)value$; break;
    case 4: season = (java.lang.CharSequence)value$; break;
    case 5: url = (java.lang.CharSequence)value$; break;
    case 6: cat = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: videoquality = (java.lang.Integer)value$; break;
    case 8: keywords = (java.lang.CharSequence)value$; break;
    case 9: contentrating = (java.lang.CharSequence)value$; break;
    case 10: userrating = (java.lang.CharSequence)value$; break;
    case 11: context = (java.lang.CharSequence)value$; break;
    case 12: livestream = (java.lang.Integer)value$; break;
    case 13: sourcerelationship = (java.lang.Integer)value$; break;
    case 14: producer = (org.openrtb.common.api.Producer)value$; break;
    case 15: len = (java.lang.Integer)value$; break;
    case 16: qagmediarating = (java.lang.Integer)value$; break;
    case 17: embeddable = (java.lang.Integer)value$; break;
    case 18: language = (java.lang.CharSequence)value$; break;
    case 19: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'episode' field.
   */
  public java.lang.Integer getEpisode() {
    return episode;
  }

  /**
   * Sets the value of the 'episode' field.
   * @param value the value to set.
   */
  public void setEpisode(java.lang.Integer value) {
    this.episode = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'series' field.
   */
  public java.lang.CharSequence getSeries() {
    return series;
  }

  /**
   * Sets the value of the 'series' field.
   * @param value the value to set.
   */
  public void setSeries(java.lang.CharSequence value) {
    this.series = value;
  }

  /**
   * Gets the value of the 'season' field.
   */
  public java.lang.CharSequence getSeason() {
    return season;
  }

  /**
   * Sets the value of the 'season' field.
   * @param value the value to set.
   */
  public void setSeason(java.lang.CharSequence value) {
    this.season = value;
  }

  /**
   * Gets the value of the 'url' field.
   */
  public java.lang.CharSequence getUrl() {
    return url;
  }

  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.CharSequence value) {
    this.url = value;
  }

  /**
   * Gets the value of the 'cat' field.
   */
  public java.util.List<java.lang.CharSequence> getCat() {
    return cat;
  }

  /**
   * Sets the value of the 'cat' field.
   * @param value the value to set.
   */
  public void setCat(java.util.List<java.lang.CharSequence> value) {
    this.cat = value;
  }

  /**
   * Gets the value of the 'videoquality' field.
   */
  public java.lang.Integer getVideoquality() {
    return videoquality;
  }

  /**
   * Sets the value of the 'videoquality' field.
   * @param value the value to set.
   */
  public void setVideoquality(java.lang.Integer value) {
    this.videoquality = value;
  }

  /**
   * Gets the value of the 'keywords' field.
   */
  public java.lang.CharSequence getKeywords() {
    return keywords;
  }

  /**
   * Sets the value of the 'keywords' field.
   * @param value the value to set.
   */
  public void setKeywords(java.lang.CharSequence value) {
    this.keywords = value;
  }

  /**
   * Gets the value of the 'contentrating' field.
   */
  public java.lang.CharSequence getContentrating() {
    return contentrating;
  }

  /**
   * Sets the value of the 'contentrating' field.
   * @param value the value to set.
   */
  public void setContentrating(java.lang.CharSequence value) {
    this.contentrating = value;
  }

  /**
   * Gets the value of the 'userrating' field.
   */
  public java.lang.CharSequence getUserrating() {
    return userrating;
  }

  /**
   * Sets the value of the 'userrating' field.
   * @param value the value to set.
   */
  public void setUserrating(java.lang.CharSequence value) {
    this.userrating = value;
  }

  /**
   * Gets the value of the 'context' field.
   */
  public java.lang.CharSequence getContext() {
    return context;
  }

  /**
   * Sets the value of the 'context' field.
   * @param value the value to set.
   */
  public void setContext(java.lang.CharSequence value) {
    this.context = value;
  }

  /**
   * Gets the value of the 'livestream' field.
   */
  public java.lang.Integer getLivestream() {
    return livestream;
  }

  /**
   * Sets the value of the 'livestream' field.
   * @param value the value to set.
   */
  public void setLivestream(java.lang.Integer value) {
    this.livestream = value;
  }

  /**
   * Gets the value of the 'sourcerelationship' field.
   */
  public java.lang.Integer getSourcerelationship() {
    return sourcerelationship;
  }

  /**
   * Sets the value of the 'sourcerelationship' field.
   * @param value the value to set.
   */
  public void setSourcerelationship(java.lang.Integer value) {
    this.sourcerelationship = value;
  }

  /**
   * Gets the value of the 'producer' field.
   */
  public org.openrtb.common.api.Producer getProducer() {
    return producer;
  }

  /**
   * Sets the value of the 'producer' field.
   * @param value the value to set.
   */
  public void setProducer(org.openrtb.common.api.Producer value) {
    this.producer = value;
  }

  /**
   * Gets the value of the 'len' field.
   */
  public java.lang.Integer getLen() {
    return len;
  }

  /**
   * Sets the value of the 'len' field.
   * @param value the value to set.
   */
  public void setLen(java.lang.Integer value) {
    this.len = value;
  }

  /**
   * Gets the value of the 'qagmediarating' field.
   */
  public java.lang.Integer getQagmediarating() {
    return qagmediarating;
  }

  /**
   * Sets the value of the 'qagmediarating' field.
   * @param value the value to set.
   */
  public void setQagmediarating(java.lang.Integer value) {
    this.qagmediarating = value;
  }

  /**
   * Gets the value of the 'embeddable' field.
   */
  public java.lang.Integer getEmbeddable() {
    return embeddable;
  }

  /**
   * Sets the value of the 'embeddable' field.
   * @param value the value to set.
   */
  public void setEmbeddable(java.lang.Integer value) {
    this.embeddable = value;
  }

  /**
   * Gets the value of the 'language' field.
   */
  public java.lang.CharSequence getLanguage() {
    return language;
  }

  /**
   * Sets the value of the 'language' field.
   * @param value the value to set.
   */
  public void setLanguage(java.lang.CharSequence value) {
    this.language = value;
  }

  /**
   * Gets the value of the 'ext' field.
   */
  public java.lang.CharSequence getExt() {
    return ext;
  }

  /**
   * Sets the value of the 'ext' field.
   * @param value the value to set.
   */
  public void setExt(java.lang.CharSequence value) {
    this.ext = value;
  }

  /** Creates a new Content RecordBuilder */
  public static org.openrtb.common.api.Content.Builder newBuilder() {
    return new org.openrtb.common.api.Content.Builder();
  }
  
  /** Creates a new Content RecordBuilder by copying an existing Builder */
  public static org.openrtb.common.api.Content.Builder newBuilder(org.openrtb.common.api.Content.Builder other) {
    return new org.openrtb.common.api.Content.Builder(other);
  }
  
  /** Creates a new Content RecordBuilder by copying an existing Content instance */
  public static org.openrtb.common.api.Content.Builder newBuilder(org.openrtb.common.api.Content other) {
    return new org.openrtb.common.api.Content.Builder(other);
  }
  
  /**
   * RecordBuilder for Content instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Content>
    implements org.apache.avro.data.RecordBuilder<Content> {

    private java.lang.CharSequence id;
    private java.lang.Integer episode;
    private java.lang.CharSequence title;
    private java.lang.CharSequence series;
    private java.lang.CharSequence season;
    private java.lang.CharSequence url;
    private java.util.List<java.lang.CharSequence> cat;
    private java.lang.Integer videoquality;
    private java.lang.CharSequence keywords;
    private java.lang.CharSequence contentrating;
    private java.lang.CharSequence userrating;
    private java.lang.CharSequence context;
    private java.lang.Integer livestream;
    private java.lang.Integer sourcerelationship;
    private org.openrtb.common.api.Producer producer;
    private java.lang.Integer len;
    private java.lang.Integer qagmediarating;
    private java.lang.Integer embeddable;
    private java.lang.CharSequence language;
    private java.lang.CharSequence ext;

    /** Creates a new Builder */
    private Builder() {
      super(org.openrtb.common.api.Content.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.openrtb.common.api.Content.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Content instance */
    private Builder(org.openrtb.common.api.Content other) {
            super(org.openrtb.common.api.Content.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.episode)) {
        this.episode = data().deepCopy(fields()[1].schema(), other.episode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.series)) {
        this.series = data().deepCopy(fields()[3].schema(), other.series);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.season)) {
        this.season = data().deepCopy(fields()[4].schema(), other.season);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.url)) {
        this.url = data().deepCopy(fields()[5].schema(), other.url);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cat)) {
        this.cat = data().deepCopy(fields()[6].schema(), other.cat);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.videoquality)) {
        this.videoquality = data().deepCopy(fields()[7].schema(), other.videoquality);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.keywords)) {
        this.keywords = data().deepCopy(fields()[8].schema(), other.keywords);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.contentrating)) {
        this.contentrating = data().deepCopy(fields()[9].schema(), other.contentrating);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.userrating)) {
        this.userrating = data().deepCopy(fields()[10].schema(), other.userrating);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.context)) {
        this.context = data().deepCopy(fields()[11].schema(), other.context);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.livestream)) {
        this.livestream = data().deepCopy(fields()[12].schema(), other.livestream);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.sourcerelationship)) {
        this.sourcerelationship = data().deepCopy(fields()[13].schema(), other.sourcerelationship);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.producer)) {
        this.producer = data().deepCopy(fields()[14].schema(), other.producer);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.len)) {
        this.len = data().deepCopy(fields()[15].schema(), other.len);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.qagmediarating)) {
        this.qagmediarating = data().deepCopy(fields()[16].schema(), other.qagmediarating);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.embeddable)) {
        this.embeddable = data().deepCopy(fields()[17].schema(), other.embeddable);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.language)) {
        this.language = data().deepCopy(fields()[18].schema(), other.language);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.ext)) {
        this.ext = data().deepCopy(fields()[19].schema(), other.ext);
        fieldSetFlags()[19] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.openrtb.common.api.Content.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.openrtb.common.api.Content.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'episode' field */
    public java.lang.Integer getEpisode() {
      return episode;
    }
    
    /** Sets the value of the 'episode' field */
    public org.openrtb.common.api.Content.Builder setEpisode(java.lang.Integer value) {
      validate(fields()[1], value);
      this.episode = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'episode' field has been set */
    public boolean hasEpisode() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'episode' field */
    public org.openrtb.common.api.Content.Builder clearEpisode() {
      episode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public org.openrtb.common.api.Content.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.title = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'title' field */
    public org.openrtb.common.api.Content.Builder clearTitle() {
      title = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'series' field */
    public java.lang.CharSequence getSeries() {
      return series;
    }
    
    /** Sets the value of the 'series' field */
    public org.openrtb.common.api.Content.Builder setSeries(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.series = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'series' field has been set */
    public boolean hasSeries() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'series' field */
    public org.openrtb.common.api.Content.Builder clearSeries() {
      series = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'season' field */
    public java.lang.CharSequence getSeason() {
      return season;
    }
    
    /** Sets the value of the 'season' field */
    public org.openrtb.common.api.Content.Builder setSeason(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.season = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'season' field has been set */
    public boolean hasSeason() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'season' field */
    public org.openrtb.common.api.Content.Builder clearSeason() {
      season = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'url' field */
    public java.lang.CharSequence getUrl() {
      return url;
    }
    
    /** Sets the value of the 'url' field */
    public org.openrtb.common.api.Content.Builder setUrl(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.url = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'url' field has been set */
    public boolean hasUrl() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'url' field */
    public org.openrtb.common.api.Content.Builder clearUrl() {
      url = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'cat' field */
    public java.util.List<java.lang.CharSequence> getCat() {
      return cat;
    }
    
    /** Sets the value of the 'cat' field */
    public org.openrtb.common.api.Content.Builder setCat(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[6], value);
      this.cat = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'cat' field has been set */
    public boolean hasCat() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'cat' field */
    public org.openrtb.common.api.Content.Builder clearCat() {
      cat = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'videoquality' field */
    public java.lang.Integer getVideoquality() {
      return videoquality;
    }
    
    /** Sets the value of the 'videoquality' field */
    public org.openrtb.common.api.Content.Builder setVideoquality(java.lang.Integer value) {
      validate(fields()[7], value);
      this.videoquality = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'videoquality' field has been set */
    public boolean hasVideoquality() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'videoquality' field */
    public org.openrtb.common.api.Content.Builder clearVideoquality() {
      videoquality = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'keywords' field */
    public java.lang.CharSequence getKeywords() {
      return keywords;
    }
    
    /** Sets the value of the 'keywords' field */
    public org.openrtb.common.api.Content.Builder setKeywords(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.keywords = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'keywords' field has been set */
    public boolean hasKeywords() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'keywords' field */
    public org.openrtb.common.api.Content.Builder clearKeywords() {
      keywords = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'contentrating' field */
    public java.lang.CharSequence getContentrating() {
      return contentrating;
    }
    
    /** Sets the value of the 'contentrating' field */
    public org.openrtb.common.api.Content.Builder setContentrating(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.contentrating = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'contentrating' field has been set */
    public boolean hasContentrating() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'contentrating' field */
    public org.openrtb.common.api.Content.Builder clearContentrating() {
      contentrating = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'userrating' field */
    public java.lang.CharSequence getUserrating() {
      return userrating;
    }
    
    /** Sets the value of the 'userrating' field */
    public org.openrtb.common.api.Content.Builder setUserrating(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.userrating = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'userrating' field has been set */
    public boolean hasUserrating() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'userrating' field */
    public org.openrtb.common.api.Content.Builder clearUserrating() {
      userrating = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'context' field */
    public java.lang.CharSequence getContext() {
      return context;
    }
    
    /** Sets the value of the 'context' field */
    public org.openrtb.common.api.Content.Builder setContext(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.context = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'context' field has been set */
    public boolean hasContext() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'context' field */
    public org.openrtb.common.api.Content.Builder clearContext() {
      context = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'livestream' field */
    public java.lang.Integer getLivestream() {
      return livestream;
    }
    
    /** Sets the value of the 'livestream' field */
    public org.openrtb.common.api.Content.Builder setLivestream(java.lang.Integer value) {
      validate(fields()[12], value);
      this.livestream = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'livestream' field has been set */
    public boolean hasLivestream() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'livestream' field */
    public org.openrtb.common.api.Content.Builder clearLivestream() {
      livestream = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'sourcerelationship' field */
    public java.lang.Integer getSourcerelationship() {
      return sourcerelationship;
    }
    
    /** Sets the value of the 'sourcerelationship' field */
    public org.openrtb.common.api.Content.Builder setSourcerelationship(java.lang.Integer value) {
      validate(fields()[13], value);
      this.sourcerelationship = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'sourcerelationship' field has been set */
    public boolean hasSourcerelationship() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'sourcerelationship' field */
    public org.openrtb.common.api.Content.Builder clearSourcerelationship() {
      sourcerelationship = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'producer' field */
    public org.openrtb.common.api.Producer getProducer() {
      return producer;
    }
    
    /** Sets the value of the 'producer' field */
    public org.openrtb.common.api.Content.Builder setProducer(org.openrtb.common.api.Producer value) {
      validate(fields()[14], value);
      this.producer = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'producer' field has been set */
    public boolean hasProducer() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'producer' field */
    public org.openrtb.common.api.Content.Builder clearProducer() {
      producer = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'len' field */
    public java.lang.Integer getLen() {
      return len;
    }
    
    /** Sets the value of the 'len' field */
    public org.openrtb.common.api.Content.Builder setLen(java.lang.Integer value) {
      validate(fields()[15], value);
      this.len = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'len' field has been set */
    public boolean hasLen() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'len' field */
    public org.openrtb.common.api.Content.Builder clearLen() {
      len = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'qagmediarating' field */
    public java.lang.Integer getQagmediarating() {
      return qagmediarating;
    }
    
    /** Sets the value of the 'qagmediarating' field */
    public org.openrtb.common.api.Content.Builder setQagmediarating(java.lang.Integer value) {
      validate(fields()[16], value);
      this.qagmediarating = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'qagmediarating' field has been set */
    public boolean hasQagmediarating() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'qagmediarating' field */
    public org.openrtb.common.api.Content.Builder clearQagmediarating() {
      qagmediarating = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'embeddable' field */
    public java.lang.Integer getEmbeddable() {
      return embeddable;
    }
    
    /** Sets the value of the 'embeddable' field */
    public org.openrtb.common.api.Content.Builder setEmbeddable(java.lang.Integer value) {
      validate(fields()[17], value);
      this.embeddable = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'embeddable' field has been set */
    public boolean hasEmbeddable() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'embeddable' field */
    public org.openrtb.common.api.Content.Builder clearEmbeddable() {
      embeddable = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'language' field */
    public java.lang.CharSequence getLanguage() {
      return language;
    }
    
    /** Sets the value of the 'language' field */
    public org.openrtb.common.api.Content.Builder setLanguage(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.language = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'language' field has been set */
    public boolean hasLanguage() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'language' field */
    public org.openrtb.common.api.Content.Builder clearLanguage() {
      language = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'ext' field */
    public java.lang.CharSequence getExt() {
      return ext;
    }
    
    /** Sets the value of the 'ext' field */
    public org.openrtb.common.api.Content.Builder setExt(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.ext = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'ext' field has been set */
    public boolean hasExt() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'ext' field */
    public org.openrtb.common.api.Content.Builder clearExt() {
      ext = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    @Override
    public Content build() {
      try {
        Content record = new Content();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.episode = fieldSetFlags()[1] ? this.episode : (java.lang.Integer) defaultValue(fields()[1]);
        record.title = fieldSetFlags()[2] ? this.title : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.series = fieldSetFlags()[3] ? this.series : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.season = fieldSetFlags()[4] ? this.season : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.url = fieldSetFlags()[5] ? this.url : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.cat = fieldSetFlags()[6] ? this.cat : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[6]);
        record.videoquality = fieldSetFlags()[7] ? this.videoquality : (java.lang.Integer) defaultValue(fields()[7]);
        record.keywords = fieldSetFlags()[8] ? this.keywords : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.contentrating = fieldSetFlags()[9] ? this.contentrating : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.userrating = fieldSetFlags()[10] ? this.userrating : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.context = fieldSetFlags()[11] ? this.context : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.livestream = fieldSetFlags()[12] ? this.livestream : (java.lang.Integer) defaultValue(fields()[12]);
        record.sourcerelationship = fieldSetFlags()[13] ? this.sourcerelationship : (java.lang.Integer) defaultValue(fields()[13]);
        record.producer = fieldSetFlags()[14] ? this.producer : (org.openrtb.common.api.Producer) defaultValue(fields()[14]);
        record.len = fieldSetFlags()[15] ? this.len : (java.lang.Integer) defaultValue(fields()[15]);
        record.qagmediarating = fieldSetFlags()[16] ? this.qagmediarating : (java.lang.Integer) defaultValue(fields()[16]);
        record.embeddable = fieldSetFlags()[17] ? this.embeddable : (java.lang.Integer) defaultValue(fields()[17]);
        record.language = fieldSetFlags()[18] ? this.language : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.ext = fieldSetFlags()[19] ? this.ext : (java.lang.CharSequence) defaultValue(fields()[19]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
