/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Device extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Device\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"dnt\",\"type\":[\"int\",\"null\"]},{\"name\":\"ua\",\"type\":[\"string\",\"null\"]},{\"name\":\"ip\",\"type\":[\"string\",\"null\"]},{\"name\":\"geo\",\"type\":[{\"type\":\"record\",\"name\":\"Geo\",\"fields\":[{\"name\":\"lat\",\"type\":[\"float\",\"null\"]},{\"name\":\"lon\",\"type\":[\"float\",\"null\"]},{\"name\":\"country\",\"type\":[\"string\",\"null\"]},{\"name\":\"region\",\"type\":[\"string\",\"null\"]},{\"name\":\"regionfips104\",\"type\":[\"string\",\"null\"]},{\"name\":\"metro\",\"type\":[\"string\",\"null\"]},{\"name\":\"city\",\"type\":[\"string\",\"null\"]},{\"name\":\"zip\",\"type\":[\"string\",\"null\"]},{\"name\":\"type\",\"type\":[\"int\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]},\"null\"]},{\"name\":\"didsha1\",\"type\":[\"string\",\"null\"]},{\"name\":\"didmd5\",\"type\":[\"string\",\"null\"]},{\"name\":\"dpidsha1\",\"type\":[\"string\",\"null\"]},{\"name\":\"dpidmd5\",\"type\":[\"string\",\"null\"]},{\"name\":\"ipv6\",\"type\":[\"string\",\"null\"]},{\"name\":\"carrier\",\"type\":[\"string\",\"null\"]},{\"name\":\"language\",\"type\":[\"string\",\"null\"]},{\"name\":\"make\",\"type\":[\"string\",\"null\"]},{\"name\":\"model\",\"type\":[\"string\",\"null\"]},{\"name\":\"os\",\"type\":[\"string\",\"null\"]},{\"name\":\"Osv\",\"type\":[\"string\",\"null\"]},{\"name\":\"Js\",\"type\":[\"int\",\"null\"]},{\"name\":\"connectiontype\",\"type\":[\"int\",\"null\"]},{\"name\":\"deviceType\",\"type\":[\"int\",\"null\"]},{\"name\":\"flashver\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.Integer dnt;
   public java.lang.CharSequence ua;
   public java.lang.CharSequence ip;
   public org.openrtb.common.api.Geo geo;
   public java.lang.CharSequence didsha1;
   public java.lang.CharSequence didmd5;
   public java.lang.CharSequence dpidsha1;
   public java.lang.CharSequence dpidmd5;
   public java.lang.CharSequence ipv6;
   public java.lang.CharSequence carrier;
   public java.lang.CharSequence language;
   public java.lang.CharSequence make;
   public java.lang.CharSequence model;
   public java.lang.CharSequence os;
   public java.lang.CharSequence Osv;
   public java.lang.Integer Js;
   public java.lang.Integer connectiontype;
   public java.lang.Integer deviceType;
   public java.lang.CharSequence flashver;
   public java.lang.CharSequence ext;

  /**
   * Default constructor.
   */
  public Device() {}

  /**
   * All-args constructor.
   */
  public Device(java.lang.Integer dnt, java.lang.CharSequence ua, java.lang.CharSequence ip, org.openrtb.common.api.Geo geo, java.lang.CharSequence didsha1, java.lang.CharSequence didmd5, java.lang.CharSequence dpidsha1, java.lang.CharSequence dpidmd5, java.lang.CharSequence ipv6, java.lang.CharSequence carrier, java.lang.CharSequence language, java.lang.CharSequence make, java.lang.CharSequence model, java.lang.CharSequence os, java.lang.CharSequence Osv, java.lang.Integer Js, java.lang.Integer connectiontype, java.lang.Integer deviceType, java.lang.CharSequence flashver, java.lang.CharSequence ext) {
    this.dnt = dnt;
    this.ua = ua;
    this.ip = ip;
    this.geo = geo;
    this.didsha1 = didsha1;
    this.didmd5 = didmd5;
    this.dpidsha1 = dpidsha1;
    this.dpidmd5 = dpidmd5;
    this.ipv6 = ipv6;
    this.carrier = carrier;
    this.language = language;
    this.make = make;
    this.model = model;
    this.os = os;
    this.Osv = Osv;
    this.Js = Js;
    this.connectiontype = connectiontype;
    this.deviceType = deviceType;
    this.flashver = flashver;
    this.ext = ext;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return dnt;
    case 1: return ua;
    case 2: return ip;
    case 3: return geo;
    case 4: return didsha1;
    case 5: return didmd5;
    case 6: return dpidsha1;
    case 7: return dpidmd5;
    case 8: return ipv6;
    case 9: return carrier;
    case 10: return language;
    case 11: return make;
    case 12: return model;
    case 13: return os;
    case 14: return Osv;
    case 15: return Js;
    case 16: return connectiontype;
    case 17: return deviceType;
    case 18: return flashver;
    case 19: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: dnt = (java.lang.Integer)value$; break;
    case 1: ua = (java.lang.CharSequence)value$; break;
    case 2: ip = (java.lang.CharSequence)value$; break;
    case 3: geo = (org.openrtb.common.api.Geo)value$; break;
    case 4: didsha1 = (java.lang.CharSequence)value$; break;
    case 5: didmd5 = (java.lang.CharSequence)value$; break;
    case 6: dpidsha1 = (java.lang.CharSequence)value$; break;
    case 7: dpidmd5 = (java.lang.CharSequence)value$; break;
    case 8: ipv6 = (java.lang.CharSequence)value$; break;
    case 9: carrier = (java.lang.CharSequence)value$; break;
    case 10: language = (java.lang.CharSequence)value$; break;
    case 11: make = (java.lang.CharSequence)value$; break;
    case 12: model = (java.lang.CharSequence)value$; break;
    case 13: os = (java.lang.CharSequence)value$; break;
    case 14: Osv = (java.lang.CharSequence)value$; break;
    case 15: Js = (java.lang.Integer)value$; break;
    case 16: connectiontype = (java.lang.Integer)value$; break;
    case 17: deviceType = (java.lang.Integer)value$; break;
    case 18: flashver = (java.lang.CharSequence)value$; break;
    case 19: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'dnt' field.
   */
  public java.lang.Integer getDnt() {
    return dnt;
  }

  /**
   * Sets the value of the 'dnt' field.
   * @param value the value to set.
   */
  public void setDnt(java.lang.Integer value) {
    this.dnt = value;
  }

  /**
   * Gets the value of the 'ua' field.
   */
  public java.lang.CharSequence getUa() {
    return ua;
  }

  /**
   * Sets the value of the 'ua' field.
   * @param value the value to set.
   */
  public void setUa(java.lang.CharSequence value) {
    this.ua = value;
  }

  /**
   * Gets the value of the 'ip' field.
   */
  public java.lang.CharSequence getIp() {
    return ip;
  }

  /**
   * Sets the value of the 'ip' field.
   * @param value the value to set.
   */
  public void setIp(java.lang.CharSequence value) {
    this.ip = value;
  }

  /**
   * Gets the value of the 'geo' field.
   */
  public org.openrtb.common.api.Geo getGeo() {
    return geo;
  }

  /**
   * Sets the value of the 'geo' field.
   * @param value the value to set.
   */
  public void setGeo(org.openrtb.common.api.Geo value) {
    this.geo = value;
  }

  /**
   * Gets the value of the 'didsha1' field.
   */
  public java.lang.CharSequence getDidsha1() {
    return didsha1;
  }

  /**
   * Sets the value of the 'didsha1' field.
   * @param value the value to set.
   */
  public void setDidsha1(java.lang.CharSequence value) {
    this.didsha1 = value;
  }

  /**
   * Gets the value of the 'didmd5' field.
   */
  public java.lang.CharSequence getDidmd5() {
    return didmd5;
  }

  /**
   * Sets the value of the 'didmd5' field.
   * @param value the value to set.
   */
  public void setDidmd5(java.lang.CharSequence value) {
    this.didmd5 = value;
  }

  /**
   * Gets the value of the 'dpidsha1' field.
   */
  public java.lang.CharSequence getDpidsha1() {
    return dpidsha1;
  }

  /**
   * Sets the value of the 'dpidsha1' field.
   * @param value the value to set.
   */
  public void setDpidsha1(java.lang.CharSequence value) {
    this.dpidsha1 = value;
  }

  /**
   * Gets the value of the 'dpidmd5' field.
   */
  public java.lang.CharSequence getDpidmd5() {
    return dpidmd5;
  }

  /**
   * Sets the value of the 'dpidmd5' field.
   * @param value the value to set.
   */
  public void setDpidmd5(java.lang.CharSequence value) {
    this.dpidmd5 = value;
  }

  /**
   * Gets the value of the 'ipv6' field.
   */
  public java.lang.CharSequence getIpv6() {
    return ipv6;
  }

  /**
   * Sets the value of the 'ipv6' field.
   * @param value the value to set.
   */
  public void setIpv6(java.lang.CharSequence value) {
    this.ipv6 = value;
  }

  /**
   * Gets the value of the 'carrier' field.
   */
  public java.lang.CharSequence getCarrier() {
    return carrier;
  }

  /**
   * Sets the value of the 'carrier' field.
   * @param value the value to set.
   */
  public void setCarrier(java.lang.CharSequence value) {
    this.carrier = value;
  }

  /**
   * Gets the value of the 'language' field.
   */
  public java.lang.CharSequence getLanguage() {
    return language;
  }

  /**
   * Sets the value of the 'language' field.
   * @param value the value to set.
   */
  public void setLanguage(java.lang.CharSequence value) {
    this.language = value;
  }

  /**
   * Gets the value of the 'make' field.
   */
  public java.lang.CharSequence getMake() {
    return make;
  }

  /**
   * Sets the value of the 'make' field.
   * @param value the value to set.
   */
  public void setMake(java.lang.CharSequence value) {
    this.make = value;
  }

  /**
   * Gets the value of the 'model' field.
   */
  public java.lang.CharSequence getModel() {
    return model;
  }

  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'os' field.
   */
  public java.lang.CharSequence getOs() {
    return os;
  }

  /**
   * Sets the value of the 'os' field.
   * @param value the value to set.
   */
  public void setOs(java.lang.CharSequence value) {
    this.os = value;
  }

  /**
   * Gets the value of the 'Osv' field.
   */
  public java.lang.CharSequence getOsv() {
    return Osv;
  }

  /**
   * Sets the value of the 'Osv' field.
   * @param value the value to set.
   */
  public void setOsv(java.lang.CharSequence value) {
    this.Osv = value;
  }

  /**
   * Gets the value of the 'Js' field.
   */
  public java.lang.Integer getJs() {
    return Js;
  }

  /**
   * Sets the value of the 'Js' field.
   * @param value the value to set.
   */
  public void setJs(java.lang.Integer value) {
    this.Js = value;
  }

  /**
   * Gets the value of the 'connectiontype' field.
   */
  public java.lang.Integer getConnectiontype() {
    return connectiontype;
  }

  /**
   * Sets the value of the 'connectiontype' field.
   * @param value the value to set.
   */
  public void setConnectiontype(java.lang.Integer value) {
    this.connectiontype = value;
  }

  /**
   * Gets the value of the 'deviceType' field.
   */
  public java.lang.Integer getDeviceType() {
    return deviceType;
  }

  /**
   * Sets the value of the 'deviceType' field.
   * @param value the value to set.
   */
  public void setDeviceType(java.lang.Integer value) {
    this.deviceType = value;
  }

  /**
   * Gets the value of the 'flashver' field.
   */
  public java.lang.CharSequence getFlashver() {
    return flashver;
  }

  /**
   * Sets the value of the 'flashver' field.
   * @param value the value to set.
   */
  public void setFlashver(java.lang.CharSequence value) {
    this.flashver = value;
  }

  /**
   * Gets the value of the 'ext' field.
   */
  public java.lang.CharSequence getExt() {
    return ext;
  }

  /**
   * Sets the value of the 'ext' field.
   * @param value the value to set.
   */
  public void setExt(java.lang.CharSequence value) {
    this.ext = value;
  }

  /** Creates a new Device RecordBuilder */
  public static org.openrtb.common.api.Device.Builder newBuilder() {
    return new org.openrtb.common.api.Device.Builder();
  }
  
  /** Creates a new Device RecordBuilder by copying an existing Builder */
  public static org.openrtb.common.api.Device.Builder newBuilder(org.openrtb.common.api.Device.Builder other) {
    return new org.openrtb.common.api.Device.Builder(other);
  }
  
  /** Creates a new Device RecordBuilder by copying an existing Device instance */
  public static org.openrtb.common.api.Device.Builder newBuilder(org.openrtb.common.api.Device other) {
    return new org.openrtb.common.api.Device.Builder(other);
  }
  
  /**
   * RecordBuilder for Device instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Device>
    implements org.apache.avro.data.RecordBuilder<Device> {

    private java.lang.Integer dnt;
    private java.lang.CharSequence ua;
    private java.lang.CharSequence ip;
    private org.openrtb.common.api.Geo geo;
    private java.lang.CharSequence didsha1;
    private java.lang.CharSequence didmd5;
    private java.lang.CharSequence dpidsha1;
    private java.lang.CharSequence dpidmd5;
    private java.lang.CharSequence ipv6;
    private java.lang.CharSequence carrier;
    private java.lang.CharSequence language;
    private java.lang.CharSequence make;
    private java.lang.CharSequence model;
    private java.lang.CharSequence os;
    private java.lang.CharSequence Osv;
    private java.lang.Integer Js;
    private java.lang.Integer connectiontype;
    private java.lang.Integer deviceType;
    private java.lang.CharSequence flashver;
    private java.lang.CharSequence ext;

    /** Creates a new Builder */
    private Builder() {
      super(org.openrtb.common.api.Device.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.openrtb.common.api.Device.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Device instance */
    private Builder(org.openrtb.common.api.Device other) {
            super(org.openrtb.common.api.Device.SCHEMA$);
      if (isValidValue(fields()[0], other.dnt)) {
        this.dnt = data().deepCopy(fields()[0].schema(), other.dnt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ua)) {
        this.ua = data().deepCopy(fields()[1].schema(), other.ua);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ip)) {
        this.ip = data().deepCopy(fields()[2].schema(), other.ip);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.geo)) {
        this.geo = data().deepCopy(fields()[3].schema(), other.geo);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.didsha1)) {
        this.didsha1 = data().deepCopy(fields()[4].schema(), other.didsha1);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.didmd5)) {
        this.didmd5 = data().deepCopy(fields()[5].schema(), other.didmd5);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.dpidsha1)) {
        this.dpidsha1 = data().deepCopy(fields()[6].schema(), other.dpidsha1);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.dpidmd5)) {
        this.dpidmd5 = data().deepCopy(fields()[7].schema(), other.dpidmd5);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ipv6)) {
        this.ipv6 = data().deepCopy(fields()[8].schema(), other.ipv6);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.carrier)) {
        this.carrier = data().deepCopy(fields()[9].schema(), other.carrier);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.language)) {
        this.language = data().deepCopy(fields()[10].schema(), other.language);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.make)) {
        this.make = data().deepCopy(fields()[11].schema(), other.make);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.model)) {
        this.model = data().deepCopy(fields()[12].schema(), other.model);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.os)) {
        this.os = data().deepCopy(fields()[13].schema(), other.os);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.Osv)) {
        this.Osv = data().deepCopy(fields()[14].schema(), other.Osv);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.Js)) {
        this.Js = data().deepCopy(fields()[15].schema(), other.Js);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.connectiontype)) {
        this.connectiontype = data().deepCopy(fields()[16].schema(), other.connectiontype);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[17].schema(), other.deviceType);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.flashver)) {
        this.flashver = data().deepCopy(fields()[18].schema(), other.flashver);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.ext)) {
        this.ext = data().deepCopy(fields()[19].schema(), other.ext);
        fieldSetFlags()[19] = true;
      }
    }

    /** Gets the value of the 'dnt' field */
    public java.lang.Integer getDnt() {
      return dnt;
    }
    
    /** Sets the value of the 'dnt' field */
    public org.openrtb.common.api.Device.Builder setDnt(java.lang.Integer value) {
      validate(fields()[0], value);
      this.dnt = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'dnt' field has been set */
    public boolean hasDnt() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'dnt' field */
    public org.openrtb.common.api.Device.Builder clearDnt() {
      dnt = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'ua' field */
    public java.lang.CharSequence getUa() {
      return ua;
    }
    
    /** Sets the value of the 'ua' field */
    public org.openrtb.common.api.Device.Builder setUa(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.ua = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'ua' field has been set */
    public boolean hasUa() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'ua' field */
    public org.openrtb.common.api.Device.Builder clearUa() {
      ua = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'ip' field */
    public java.lang.CharSequence getIp() {
      return ip;
    }
    
    /** Sets the value of the 'ip' field */
    public org.openrtb.common.api.Device.Builder setIp(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ip = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'ip' field has been set */
    public boolean hasIp() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'ip' field */
    public org.openrtb.common.api.Device.Builder clearIp() {
      ip = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'geo' field */
    public org.openrtb.common.api.Geo getGeo() {
      return geo;
    }
    
    /** Sets the value of the 'geo' field */
    public org.openrtb.common.api.Device.Builder setGeo(org.openrtb.common.api.Geo value) {
      validate(fields()[3], value);
      this.geo = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'geo' field has been set */
    public boolean hasGeo() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'geo' field */
    public org.openrtb.common.api.Device.Builder clearGeo() {
      geo = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'didsha1' field */
    public java.lang.CharSequence getDidsha1() {
      return didsha1;
    }
    
    /** Sets the value of the 'didsha1' field */
    public org.openrtb.common.api.Device.Builder setDidsha1(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.didsha1 = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'didsha1' field has been set */
    public boolean hasDidsha1() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'didsha1' field */
    public org.openrtb.common.api.Device.Builder clearDidsha1() {
      didsha1 = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'didmd5' field */
    public java.lang.CharSequence getDidmd5() {
      return didmd5;
    }
    
    /** Sets the value of the 'didmd5' field */
    public org.openrtb.common.api.Device.Builder setDidmd5(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.didmd5 = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'didmd5' field has been set */
    public boolean hasDidmd5() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'didmd5' field */
    public org.openrtb.common.api.Device.Builder clearDidmd5() {
      didmd5 = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'dpidsha1' field */
    public java.lang.CharSequence getDpidsha1() {
      return dpidsha1;
    }
    
    /** Sets the value of the 'dpidsha1' field */
    public org.openrtb.common.api.Device.Builder setDpidsha1(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.dpidsha1 = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'dpidsha1' field has been set */
    public boolean hasDpidsha1() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'dpidsha1' field */
    public org.openrtb.common.api.Device.Builder clearDpidsha1() {
      dpidsha1 = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'dpidmd5' field */
    public java.lang.CharSequence getDpidmd5() {
      return dpidmd5;
    }
    
    /** Sets the value of the 'dpidmd5' field */
    public org.openrtb.common.api.Device.Builder setDpidmd5(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.dpidmd5 = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'dpidmd5' field has been set */
    public boolean hasDpidmd5() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'dpidmd5' field */
    public org.openrtb.common.api.Device.Builder clearDpidmd5() {
      dpidmd5 = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'ipv6' field */
    public java.lang.CharSequence getIpv6() {
      return ipv6;
    }
    
    /** Sets the value of the 'ipv6' field */
    public org.openrtb.common.api.Device.Builder setIpv6(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.ipv6 = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'ipv6' field has been set */
    public boolean hasIpv6() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'ipv6' field */
    public org.openrtb.common.api.Device.Builder clearIpv6() {
      ipv6 = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'carrier' field */
    public java.lang.CharSequence getCarrier() {
      return carrier;
    }
    
    /** Sets the value of the 'carrier' field */
    public org.openrtb.common.api.Device.Builder setCarrier(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.carrier = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'carrier' field has been set */
    public boolean hasCarrier() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'carrier' field */
    public org.openrtb.common.api.Device.Builder clearCarrier() {
      carrier = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'language' field */
    public java.lang.CharSequence getLanguage() {
      return language;
    }
    
    /** Sets the value of the 'language' field */
    public org.openrtb.common.api.Device.Builder setLanguage(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.language = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'language' field has been set */
    public boolean hasLanguage() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'language' field */
    public org.openrtb.common.api.Device.Builder clearLanguage() {
      language = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'make' field */
    public java.lang.CharSequence getMake() {
      return make;
    }
    
    /** Sets the value of the 'make' field */
    public org.openrtb.common.api.Device.Builder setMake(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.make = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'make' field has been set */
    public boolean hasMake() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'make' field */
    public org.openrtb.common.api.Device.Builder clearMake() {
      make = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'model' field */
    public java.lang.CharSequence getModel() {
      return model;
    }
    
    /** Sets the value of the 'model' field */
    public org.openrtb.common.api.Device.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.model = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'model' field has been set */
    public boolean hasModel() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'model' field */
    public org.openrtb.common.api.Device.Builder clearModel() {
      model = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'os' field */
    public java.lang.CharSequence getOs() {
      return os;
    }
    
    /** Sets the value of the 'os' field */
    public org.openrtb.common.api.Device.Builder setOs(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.os = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'os' field has been set */
    public boolean hasOs() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'os' field */
    public org.openrtb.common.api.Device.Builder clearOs() {
      os = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'Osv' field */
    public java.lang.CharSequence getOsv() {
      return Osv;
    }
    
    /** Sets the value of the 'Osv' field */
    public org.openrtb.common.api.Device.Builder setOsv(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.Osv = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'Osv' field has been set */
    public boolean hasOsv() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'Osv' field */
    public org.openrtb.common.api.Device.Builder clearOsv() {
      Osv = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'Js' field */
    public java.lang.Integer getJs() {
      return Js;
    }
    
    /** Sets the value of the 'Js' field */
    public org.openrtb.common.api.Device.Builder setJs(java.lang.Integer value) {
      validate(fields()[15], value);
      this.Js = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'Js' field has been set */
    public boolean hasJs() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'Js' field */
    public org.openrtb.common.api.Device.Builder clearJs() {
      Js = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'connectiontype' field */
    public java.lang.Integer getConnectiontype() {
      return connectiontype;
    }
    
    /** Sets the value of the 'connectiontype' field */
    public org.openrtb.common.api.Device.Builder setConnectiontype(java.lang.Integer value) {
      validate(fields()[16], value);
      this.connectiontype = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'connectiontype' field has been set */
    public boolean hasConnectiontype() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'connectiontype' field */
    public org.openrtb.common.api.Device.Builder clearConnectiontype() {
      connectiontype = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'deviceType' field */
    public java.lang.Integer getDeviceType() {
      return deviceType;
    }
    
    /** Sets the value of the 'deviceType' field */
    public org.openrtb.common.api.Device.Builder setDeviceType(java.lang.Integer value) {
      validate(fields()[17], value);
      this.deviceType = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'deviceType' field has been set */
    public boolean hasDeviceType() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'deviceType' field */
    public org.openrtb.common.api.Device.Builder clearDeviceType() {
      deviceType = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'flashver' field */
    public java.lang.CharSequence getFlashver() {
      return flashver;
    }
    
    /** Sets the value of the 'flashver' field */
    public org.openrtb.common.api.Device.Builder setFlashver(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.flashver = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'flashver' field has been set */
    public boolean hasFlashver() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'flashver' field */
    public org.openrtb.common.api.Device.Builder clearFlashver() {
      flashver = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'ext' field */
    public java.lang.CharSequence getExt() {
      return ext;
    }
    
    /** Sets the value of the 'ext' field */
    public org.openrtb.common.api.Device.Builder setExt(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.ext = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'ext' field has been set */
    public boolean hasExt() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'ext' field */
    public org.openrtb.common.api.Device.Builder clearExt() {
      ext = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    @Override
    public Device build() {
      try {
        Device record = new Device();
        record.dnt = fieldSetFlags()[0] ? this.dnt : (java.lang.Integer) defaultValue(fields()[0]);
        record.ua = fieldSetFlags()[1] ? this.ua : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.ip = fieldSetFlags()[2] ? this.ip : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.geo = fieldSetFlags()[3] ? this.geo : (org.openrtb.common.api.Geo) defaultValue(fields()[3]);
        record.didsha1 = fieldSetFlags()[4] ? this.didsha1 : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.didmd5 = fieldSetFlags()[5] ? this.didmd5 : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.dpidsha1 = fieldSetFlags()[6] ? this.dpidsha1 : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.dpidmd5 = fieldSetFlags()[7] ? this.dpidmd5 : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.ipv6 = fieldSetFlags()[8] ? this.ipv6 : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.carrier = fieldSetFlags()[9] ? this.carrier : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.language = fieldSetFlags()[10] ? this.language : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.make = fieldSetFlags()[11] ? this.make : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.model = fieldSetFlags()[12] ? this.model : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.os = fieldSetFlags()[13] ? this.os : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.Osv = fieldSetFlags()[14] ? this.Osv : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.Js = fieldSetFlags()[15] ? this.Js : (java.lang.Integer) defaultValue(fields()[15]);
        record.connectiontype = fieldSetFlags()[16] ? this.connectiontype : (java.lang.Integer) defaultValue(fields()[16]);
        record.deviceType = fieldSetFlags()[17] ? this.deviceType : (java.lang.Integer) defaultValue(fields()[17]);
        record.flashver = fieldSetFlags()[18] ? this.flashver : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.ext = fieldSetFlags()[19] ? this.ext : (java.lang.CharSequence) defaultValue(fields()[19]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
