/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SeatBid extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SeatBid\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"bid\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Bid\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"impid\",\"type\":[\"string\",\"null\"]},{\"name\":\"price\",\"type\":[\"float\",\"null\"]},{\"name\":\"adid\",\"type\":[\"string\",\"null\"]},{\"name\":\"nurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"adm\",\"type\":[\"string\",\"null\"]},{\"name\":\"adomain\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"]},{\"name\":\"iurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"cid\",\"type\":[\"string\",\"null\"]},{\"name\":\"crid\",\"type\":[\"string\",\"null\"]},{\"name\":\"attr\",\"type\":[{\"type\":\"array\",\"items\":\"int\"},\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}}},{\"name\":\"seat\",\"type\":[\"string\",\"null\"]},{\"name\":\"group\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<org.openrtb.common.api.Bid> bid;
  @Deprecated public java.lang.CharSequence seat;
  @Deprecated public java.lang.CharSequence group;
  @Deprecated public java.lang.CharSequence ext;

  /**
   * Default constructor.
   */
  public SeatBid() {}

  /**
   * All-args constructor.
   */
  public SeatBid(java.util.List<org.openrtb.common.api.Bid> bid, java.lang.CharSequence seat, java.lang.CharSequence group, java.lang.CharSequence ext) {
    this.bid = bid;
    this.seat = seat;
    this.group = group;
    this.ext = ext;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bid;
    case 1: return seat;
    case 2: return group;
    case 3: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bid = (java.util.List<org.openrtb.common.api.Bid>)value$; break;
    case 1: seat = (java.lang.CharSequence)value$; break;
    case 2: group = (java.lang.CharSequence)value$; break;
    case 3: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'bid' field.
   */
  public java.util.List<org.openrtb.common.api.Bid> getBid() {
    return bid;
  }

  /**
   * Sets the value of the 'bid' field.
   * @param value the value to set.
   */
  public void setBid(java.util.List<org.openrtb.common.api.Bid> value) {
    this.bid = value;
  }

  /**
   * Gets the value of the 'seat' field.
   */
  public java.lang.CharSequence getSeat() {
    return seat;
  }

  /**
   * Sets the value of the 'seat' field.
   * @param value the value to set.
   */
  public void setSeat(java.lang.CharSequence value) {
    this.seat = value;
  }

  /**
   * Gets the value of the 'group' field.
   */
  public java.lang.CharSequence getGroup() {
    return group;
  }

  /**
   * Sets the value of the 'group' field.
   * @param value the value to set.
   */
  public void setGroup(java.lang.CharSequence value) {
    this.group = value;
  }

  /**
   * Gets the value of the 'ext' field.
   */
  public java.lang.CharSequence getExt() {
    return ext;
  }

  /**
   * Sets the value of the 'ext' field.
   * @param value the value to set.
   */
  public void setExt(java.lang.CharSequence value) {
    this.ext = value;
  }

  /** Creates a new SeatBid RecordBuilder */
  public static org.openrtb.common.api.SeatBid.Builder newBuilder() {
    return new org.openrtb.common.api.SeatBid.Builder();
  }
  
  /** Creates a new SeatBid RecordBuilder by copying an existing Builder */
  public static org.openrtb.common.api.SeatBid.Builder newBuilder(org.openrtb.common.api.SeatBid.Builder other) {
    return new org.openrtb.common.api.SeatBid.Builder(other);
  }
  
  /** Creates a new SeatBid RecordBuilder by copying an existing SeatBid instance */
  public static org.openrtb.common.api.SeatBid.Builder newBuilder(org.openrtb.common.api.SeatBid other) {
    return new org.openrtb.common.api.SeatBid.Builder(other);
  }
  
  /**
   * RecordBuilder for SeatBid instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SeatBid>
    implements org.apache.avro.data.RecordBuilder<SeatBid> {

    private java.util.List<org.openrtb.common.api.Bid> bid;
    private java.lang.CharSequence seat;
    private java.lang.CharSequence group;
    private java.lang.CharSequence ext;

    /** Creates a new Builder */
    private Builder() {
      super(org.openrtb.common.api.SeatBid.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.openrtb.common.api.SeatBid.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing SeatBid instance */
    private Builder(org.openrtb.common.api.SeatBid other) {
            super(org.openrtb.common.api.SeatBid.SCHEMA$);
      if (isValidValue(fields()[0], other.bid)) {
        this.bid = data().deepCopy(fields()[0].schema(), other.bid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.seat)) {
        this.seat = data().deepCopy(fields()[1].schema(), other.seat);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.group)) {
        this.group = data().deepCopy(fields()[2].schema(), other.group);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ext)) {
        this.ext = data().deepCopy(fields()[3].schema(), other.ext);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'bid' field */
    public java.util.List<org.openrtb.common.api.Bid> getBid() {
      return bid;
    }
    
    /** Sets the value of the 'bid' field */
    public org.openrtb.common.api.SeatBid.Builder setBid(java.util.List<org.openrtb.common.api.Bid> value) {
      validate(fields()[0], value);
      this.bid = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'bid' field has been set */
    public boolean hasBid() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'bid' field */
    public org.openrtb.common.api.SeatBid.Builder clearBid() {
      bid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'seat' field */
    public java.lang.CharSequence getSeat() {
      return seat;
    }
    
    /** Sets the value of the 'seat' field */
    public org.openrtb.common.api.SeatBid.Builder setSeat(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.seat = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'seat' field has been set */
    public boolean hasSeat() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'seat' field */
    public org.openrtb.common.api.SeatBid.Builder clearSeat() {
      seat = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'group' field */
    public java.lang.CharSequence getGroup() {
      return group;
    }
    
    /** Sets the value of the 'group' field */
    public org.openrtb.common.api.SeatBid.Builder setGroup(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.group = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'group' field has been set */
    public boolean hasGroup() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'group' field */
    public org.openrtb.common.api.SeatBid.Builder clearGroup() {
      group = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ext' field */
    public java.lang.CharSequence getExt() {
      return ext;
    }
    
    /** Sets the value of the 'ext' field */
    public org.openrtb.common.api.SeatBid.Builder setExt(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ext = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ext' field has been set */
    public boolean hasExt() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ext' field */
    public org.openrtb.common.api.SeatBid.Builder clearExt() {
      ext = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public SeatBid build() {
      try {
        SeatBid record = new SeatBid();
        record.bid = fieldSetFlags()[0] ? this.bid : (java.util.List<org.openrtb.common.api.Bid>) defaultValue(fields()[0]);
        record.seat = fieldSetFlags()[1] ? this.seat : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.group = fieldSetFlags()[2] ? this.group : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ext = fieldSetFlags()[3] ? this.ext : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
